language: rust

sudo: required

rust:
  - nightly

cache:
  directories:
    - $HOME/.rustup
    - $HOME/kcov

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - git

after_success: |
  git clone https://github.com/SimonKagstrom/kcov.git &&
  cd kcov &&
  cmake . &&
  make &&
  make install DESTDIR=../kcov-build &&
  cd .. &&
  for file in target/debug/clumsy-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib,tests.rs --verify "target/cov/$(basename $file)" "$file"; done &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
