[package]
name = "cli"
version = "0.1.0"
authors = ["Mizki SUZUMORI <suzumorimizuki@gmail.com>"]

[[bin]]
name = "clumsy"
path = "src/main.rs"

[dependencies]
rustyline = "1.0"
ansi_term = "0.11"
structopt = "0.2"

[dependencies.clumsy]
path = ".."
